global:
  scrape_interval: 30s
  evaluation_interval: 30s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'Server Monitoring'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - rules.yaml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'

scrape_configs:

  - job_name: 'Prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090','cadvisor:8080','node-exporter:9100']